"""Two-stage FR3 payload identification with explicit observability gates.

This module is deliberately independent from :mod:`payload_id`.  The latter
implements the historical ten-parameter, one-shot excitation and is kept for
audit/reproduction.  ``payload_id_v2`` separates the well-conditioned part of
the problem (mass and first moment from static gravity measurements) from the
usually poorly observable rotational inertia.  No ground-truth values are
read here; a mesh is only used by the explicit geometry fallback.

The recorder schema is intentionally small and portable.  A record contains
the original torque/pose/Jacobian arrays and, for v2 captures, the analytic
``q_ref``, ``dq_ref`` and ``ddq_ref`` generated by ``payload_skill_v2``.  This
lets the dynamic stage use the known smooth excitation instead of taking raw
finite differences of a noisy velocity signal.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
from scipy.signal import butter, savgol_filter, sosfiltfilt
from scipy.spatial.transform import Rotation


PARAMETER_ORDER = ("m", "hx", "hy", "hz", "Ixx", "Ixy", "Ixz", "Iyy", "Iyz", "Izz")
STATIC_PARAMETER_ORDER = ("m", "hx", "hy", "hz")
INERTIA_PARAMETER_ORDER = ("Ixx", "Ixy", "Ixz", "Iyy", "Iyz", "Izz")
GRAVITY = np.array([0.0, 0.0, -9.81])


def _skew(v: np.ndarray) -> np.ndarray:
    x, y, z = np.asarray(v, dtype=float)
    return np.array([[0.0, -z, y], [z, 0.0, -x], [-y, x, 0.0]])


def _as_bool(value: Any, default: bool = False) -> bool:
    if value is None:
        return default
    arr = np.asarray(value).reshape(-1)
    return bool(arr[-1]) if len(arr) else default


def load_record(path: Path | str) -> dict[str, np.ndarray]:
    """Load an NPZ capture and validate the common, non-GT fields."""
    with np.load(Path(path), allow_pickle=True) as data:
        result = {key: np.asarray(data[key]) for key in data.files}
    required = {"t", "q", "dq", "tau", "T_B_TCP", "jacobian_TCP"}
    missing = required - set(result)
    if missing:
        raise ValueError(f"payload record missing {sorted(missing)}")
    n = len(result["t"])
    if any(len(result[key]) != n for key in ("q", "dq", "tau", "T_B_TCP", "jacobian_TCP")):
        raise ValueError("payload record arrays have inconsistent lengths")
    return result


def _time(record: dict[str, np.ndarray]) -> np.ndarray:
    t = np.asarray(record["t"], dtype=float).reshape(-1)
    if len(t) < 2 or not np.all(np.isfinite(t)):
        raise ValueError("record has no usable timestamps")
    t = t - t[0]
    if np.any(np.diff(t) <= 0):
        raise ValueError("record timestamps are not strictly increasing")
    return t


def align_baseline(baseline: dict[str, np.ndarray], payload: dict[str, np.ndarray],
                   duration_tolerance_s: float = 0.05) -> tuple[np.ndarray, np.ndarray]:
    """Interpolate empty-arm torque and q on to the payload time base."""
    t = _time(payload)
    tb = _time(baseline)
    if t[-1] > tb[-1] + duration_tolerance_s:
        raise ValueError("baseline duration is shorter than payload capture")
    tau0 = np.column_stack([np.interp(t, tb, baseline["tau"][:, j]) for j in range(7)])
    q0 = np.column_stack([np.interp(t, tb, baseline["q"][:, j]) for j in range(7)])
    # The two captures are generated from the same protocol.  A small recorder
    # quantisation error is expected, but a different path invalidates pairing.
    q_payload = np.asarray(payload["q"], dtype=float)
    # Both captures carry the analytic command sidecar generated by the
    # protocol. Compare those references when available: measured positions
    # can differ by a few samples at the start/end of two independent
    # simulator runs even though they executed the identical trajectory. A
    # measured-path comparison remains the fallback for legacy records.
    q_payload_compare = np.asarray(payload.get("q_ref", q_payload), dtype=float)
    q_baseline_compare_source = baseline.get("q_ref", baseline["q"])
    q_baseline_compare = np.column_stack([
        np.interp(t, tb, np.asarray(q_baseline_compare_source, dtype=float)[:, j])
        for j in range(7)
    ])
    if np.max(np.abs(q_baseline_compare - q_payload_compare)) > 0.04:
        raise ValueError("paired baseline joint reference path mismatch exceeds 0.04 rad")
    return tau0, q0


def _filter(values: np.ndarray, rate_hz: float, cutoff_hz: float = 4.0) -> np.ndarray:
    values = np.asarray(values, dtype=float)
    if len(values) < 30 or rate_hz <= 1.0 or cutoff_hz >= 0.45 * rate_hz:
        return values
    return sosfiltfilt(butter(4, cutoff_hz, fs=rate_hz, output="sos"), values, axis=0)


def _safe_rate(t: np.ndarray) -> float:
    return float(1.0 / np.median(np.diff(t)))


def _weighted_lstsq(X: np.ndarray, y: np.ndarray, weights: np.ndarray) -> np.ndarray:
    w = np.sqrt(np.maximum(np.asarray(weights, dtype=float), 1e-12))
    return np.linalg.lstsq(X * w[:, None], y * w, rcond=1e-10)[0]


def robust_linear_fit(X: np.ndarray, y: np.ndarray, *, max_iter: int = 30,
                      huber_k: float = 1.5) -> dict[str, Any]:
    """Huber IRLS fit with covariance and singular-value diagnostics.

    The covariance is a sandwich-style estimate based on the robust residual
    scale.  It is intentionally reported even when the observability gate
    rejects the result, so a caller can explain why a fallback was selected.
    """
    X = np.asarray(X, dtype=float)
    y = np.asarray(y, dtype=float).reshape(-1)
    good = np.isfinite(X).all(axis=1) & np.isfinite(y)
    X, y = X[good], y[good]
    if len(X) < X.shape[1]:
        raise ValueError("not enough finite samples for robust fit")
    # A high-leverage torque outlier can pull an ordinary least-squares
    # initialisation far enough that Huber IRLS never recovers.  Use a small,
    # deterministic consensus search for the initial model.  The production
    # captures have thousands of rows, so this is inexpensive; for a tiny
    # record the full least-squares fit remains the fallback.
    theta = np.linalg.lstsq(X, y, rcond=1e-10)[0]
    p = X.shape[1]
    if len(X) > p:
        rng = np.random.default_rng(20260911)
        trials = min(128, max(16, 4 * p))
        best = (float("inf"), -1, theta)
        for subset in [np.arange(p)] + [rng.choice(len(X), size=p, replace=False) for _ in range(trials)]:
            candidate = np.linalg.lstsq(X[subset], y[subset], rcond=1e-10)[0]
            err = np.abs(X @ candidate - y)
            med = float(np.median(err))
            scale0 = max(1e-9, 1.4826 * float(np.median(np.abs(err - med))))
            inlier_count = int(np.sum(err <= max(3.0 * scale0, 1e-7)))
            # Prefer the smallest median residual; use consensus count only as
            # a tie breaker.  Maximising the inlier count alone can select a
            # high-leverage model whose residual scale is inflated by the
            # outlier itself.
            score = (med, -inlier_count)
            if score < (best[0], best[1]):
                best = (med, -inlier_count, candidate)
        theta = best[2]
    weights = np.ones(len(y), dtype=float)
    for _ in range(max_iter):
        residual = X @ theta - y
        mad = np.median(np.abs(residual - np.median(residual)))
        # Do not use an RMS floor here: one large outlier would inflate the
        # scale and make every row look like an inlier.  A zero MAD is valid
        # for an exact consensus, so retain a tiny numerical scale instead.
        scale = max(1e-9, 1.4826 * float(mad))
        u = np.abs(residual) / (huber_k * scale)
        new_weights = np.where(u <= 1.0, 1.0, 1.0 / np.maximum(u, 1e-12))
        new_theta = _weighted_lstsq(X, y, new_weights)
        if np.linalg.norm(new_theta - theta) <= 1e-9 * (1.0 + np.linalg.norm(theta)):
            theta = new_theta
            weights = new_weights
            break
        theta, weights = new_theta, new_weights
    residual = X @ theta - y
    mad = np.median(np.abs(residual - np.median(residual)))
    scale = max(1e-9, 1.4826 * float(mad))
    # Robust covariance, with a small Tikhonov term only for numerical safety.
    normal = X.T @ (weights[:, None] * X)
    inv_normal = np.linalg.pinv(normal, rcond=1e-10)
    psi = np.clip(residual / scale, -huber_k, huber_k)
    meat = X.T @ ((psi * psi)[:, None] * X)
    covariance = inv_normal @ meat @ inv_normal * scale * scale
    singular = np.linalg.svd(X, compute_uv=False)
    sigma_min = float(singular[-1]) if len(singular) else 0.0
    sigma_max = float(singular[0]) if len(singular) else 0.0
    condition = float(sigma_max / sigma_min) if sigma_min > 1e-14 else float("inf")
    inliers = np.abs(residual) <= max(3.0 * scale, 1e-8)
    return {
        "theta": theta,
        "residual": residual,
        "weights": weights,
        "covariance": covariance,
        "sigma_min": sigma_min,
        "sigma_max": sigma_max,
        "condition_number": condition,
        "residual_rms_Nm": float(np.sqrt(np.mean(residual**2))),
        "robust_scale_Nm": float(scale),
        "outlier_fraction": float(1.0 - np.mean(inliers)),
        "inlier_count": int(np.sum(inliers)),
        "sample_count": int(len(y)),
        "rank": int(np.linalg.matrix_rank(X, tol=max(sigma_max, 1.0) * 1e-10)),
    }


def _record_guard_ok(record: dict[str, np.ndarray]) -> bool:
    return _as_bool(record.get("guard_passed"), False)


def static_gravity_regressor(record: dict[str, np.ndarray]) -> np.ndarray:
    """Return one 7x4 gravity regressor per record sample.

    Parameters are ``[mass, m*cx, m*cy, m*cz]`` in ``fr3_hand_tcp``.  The
    gravity vector is expressed in the robot base frame and the measured TCP
    Jacobian maps base-frame wrench to joint torque.
    """
    T = np.asarray(record["T_B_TCP"], dtype=float)
    J = np.asarray(record["jacobian_TCP"], dtype=float)
    rows = []
    effective_a = -GRAVITY
    basis = np.eye(3)
    for i in range(len(T)):
        R = T[i, :3, :3]
        Jv, Jw = J[i, :3, :7], J[i, 3:, :7]
        columns = [Jv.T @ effective_a]
        for e in basis:
            h = R @ e
            columns.append(Jw.T @ np.cross(h, effective_a))
        rows.append(np.stack(columns, axis=1))
    return np.asarray(rows)


def _protocol_array(record: dict[str, np.ndarray], key: str, n: int,
                    default: np.ndarray | None = None) -> np.ndarray | None:
    if key in record:
        value = np.asarray(record[key], dtype=float)
        if value.ndim == 1:
            value = value[:, None]
        if len(value) == n:
            return value
    return default


def _static_mask(record: dict[str, np.ndarray], protocol: dict[str, Any] | None) -> tuple[np.ndarray, np.ndarray]:
    n = len(record["t"])
    if "static_hold" in record:
        hold = np.asarray(record["static_hold"]).reshape(-1).astype(bool)
        pose_id = np.asarray(record.get("static_pose_id", np.full(n, -1))).reshape(-1).astype(int)
        if len(hold) == n:
            return hold, pose_id
    if protocol:
        t = _time(record)
        pt = np.asarray(protocol.get("time", []), dtype=float)
        ph = np.asarray(protocol.get("static_hold", []), dtype=bool)
        pp = np.asarray(protocol.get("static_pose_id", []), dtype=int)
        if len(pt) and len(pt) == len(ph):
            return np.interp(t, pt, ph.astype(float), left=0, right=0) > .5, np.rint(np.interp(t, pt, pp, left=-1, right=-1)).astype(int)
    # Legacy/static fallback: only low-reference-speed samples are used.
    dq = np.asarray(record.get("dq", np.zeros((n, 7))), dtype=float)
    ddq = np.asarray(record.get("ddq_ref", np.zeros_like(dq)), dtype=float)
    return (np.linalg.norm(dq, axis=1) < 0.02) & (np.linalg.norm(ddq, axis=1) < .2), np.full(n, -1, dtype=int)


def static_gravity_identify(baseline: dict[str, np.ndarray], payload: dict[str, np.ndarray],
                            protocol: dict[str, Any] | None = None,
                            *, min_postures: int = 5, max_condition: float = 1.0e4,
                            max_mass_relative_sigma: float = .15,
                            max_com_sigma_m: float = .012) -> dict[str, Any]:
    """Estimate mass and first moment from averaged static orientation holds."""
    result: dict[str, Any] = {
        "schema": "payload_id_v2/static_gravity/v1",
        "stage": "STATIC_GRAVITY_ID",
        "source": "UNOBSERVABLE",
        "accepted": False,
    }
    if not _record_guard_ok(payload):
        result.update(reason="PAYLOAD_GUARD_ABORT", guard_passed=False)
        return result
    try:
        tau0, _ = align_baseline(baseline, payload)
        T = _time(payload)
        rate = _safe_rate(T)
        delta = _filter(np.asarray(payload["tau"], float) - tau0, rate, 2.0)
        Yall = static_gravity_regressor(payload)
        hold, pose_id = _static_mask(payload, protocol)
        valid = hold & np.isfinite(delta).all(axis=1)
        ids = sorted(int(x) for x in np.unique(pose_id[valid]) if x >= 0)
        # Aggregate each hold to suppress 240 Hz contact/solver noise.  If the
        # protocol has no IDs, retain decimated static samples instead.
        Ys, ds = [], []
        if ids:
            for pid in ids:
                idx = np.flatnonzero(valid & (pose_id == pid))
                if len(idx) < max(3, int(.15 * rate)):
                    continue
                Ys.append(np.mean(Yall[idx], axis=0))
                ds.append(np.mean(delta[idx], axis=0))
        else:
            idx = np.flatnonzero(valid)
            for start in idx[::max(1, int(.15 * rate))]:
                window = idx[(idx >= start) & (idx < start + max(3, int(.15 * rate)))]
                if len(window):
                    Ys.append(np.mean(Yall[window], axis=0)); ds.append(np.mean(delta[window], axis=0))
        if len(Ys) < min_postures:
            result.update(reason="INSUFFICIENT_STATIC_POSTURES", posture_count=len(Ys), guard_passed=True)
            return result
        # Stack joint rows; each posture contributes seven torque equations.
        fit = robust_linear_fit(np.concatenate(Ys, axis=0), np.concatenate(ds, axis=0))
        theta = fit["theta"]
        mass = float(theta[0])
        first_moment = np.asarray(theta[1:4], dtype=float)
        com = first_moment / mass if abs(mass) > 1e-8 else np.full(3, np.nan)
        cov = np.asarray(fit["covariance"], dtype=float)
        mass_sigma = float(np.sqrt(max(cov[0, 0], 0.0)))
        Jcom = np.zeros((3, 4)); Jcom[:, 0] = -first_moment / (mass * mass); Jcom[:, 1:] = np.eye(3) / mass if abs(mass) > 1e-8 else 0.0
        com_cov = Jcom @ cov @ Jcom.T if np.isfinite(Jcom).all() else np.full((3, 3), np.inf)
        com_sigma = float(np.sqrt(max(np.trace(com_cov), 0.0))) if np.isfinite(com_cov).all() else float("inf")
        physical = bool(np.isfinite(mass) and mass > 0 and np.isfinite(com).all() and np.linalg.norm(com) < .25)
        observable = bool(fit["rank"] >= 4 and fit["condition_number"] <= max_condition and physical and
                          mass_sigma <= max_mass_relative_sigma * mass and com_sigma <= max_com_sigma_m)
        result.update(
            accepted=observable, source="STATIC_GRAVITY_ID" if observable else "UNOBSERVABLE",
            reason="OK" if observable else "STATIC_UNCERTAIN", guard_passed=True,
            mass_kg=mass, first_moment_kg_m=first_moment.tolist(), center_of_mass_m=com.tolist(),
            parameter_order=list(STATIC_PARAMETER_ORDER), parameter_covariance=cov.tolist(),
            center_of_mass_covariance_m2=com_cov.tolist(), parameter_std= np.sqrt(np.maximum(np.diag(cov), 0)).tolist(),
            mass_sigma_kg=mass_sigma, center_of_mass_sigma_m=com_sigma,
            observability={"sigma_min":fit["sigma_min"], "sigma_max":fit["sigma_max"], "condition_number":fit["condition_number"], "rank":fit["rank"]},
            residual_rms_Nm=fit["residual_rms_Nm"], robust_scale_Nm=fit["robust_scale_Nm"],
            outlier_fraction=fit["outlier_fraction"], inlier_count=fit["inlier_count"],
            samples=fit["sample_count"], postures=len(Ys), physical_checks={"mass_positive":mass>0,"com_finite":bool(np.isfinite(com).all()),"com_within_0.25m":bool(np.linalg.norm(com)<.25)},
        )
        return result
    except Exception as exc:
        result.update(reason="STATIC_ESTIMATOR_ERROR", error=str(exc))
        return result


def _analytic_task_kinematics(record: dict[str, np.ndarray]) -> tuple[np.ndarray, np.ndarray, np.ndarray, str]:
    """Compute task kinematics using analytic joint references and Jdot.

    The smooth protocol provides q/dq/ddq.  The measured Jacobian is filtered
    before its time derivative is taken, so no noisy raw velocity difference is
    used.  For old records without references, a documented filtered pose
    fallback is used.
    """
    t = _time(record); rate = _safe_rate(t); J = np.asarray(record["jacobian_TCP"], dtype=float)
    J = _filter(J, rate, 5.0)
    if all(k in record for k in ("dq_ref", "ddq_ref")):
        dq = np.asarray(record["dq_ref"], dtype=float)
        ddq = np.asarray(record["ddq_ref"], dtype=float)
        if len(dq) == len(t) and len(ddq) == len(t):
            Jdot = np.gradient(J, t, axis=0, edge_order=2)
            Jv, Jw = J[:, :3, :7], J[:, 3:, :7]
            Jvd, Jwd = Jdot[:, :3, :7], Jdot[:, 3:, :7]
            v = np.einsum("nij,nj->ni", Jv, dq)
            a = np.einsum("nij,nj->ni", Jv, ddq) + np.einsum("nij,nj->ni", Jvd, dq)
            omega = np.einsum("nij,nj->ni", Jw, dq)
            alpha = np.einsum("nij,nj->ni", Jw, ddq) + np.einsum("nij,nj->ni", Jwd, dq)
            return a, omega, alpha, "analytic_joint_reference_plus_filtered_Jdot"
    # Audit-only legacy fallback.  It remains available for old captures but
    # is never silently labelled analytic.
    p = _filter(np.asarray(record["T_B_TCP"])[:, :3, 3], rate, 5.0)
    rotations = Rotation.from_matrix(np.asarray(record["T_B_TCP"])[:, :3, :3])
    rotvec = np.unwrap(rotations.as_rotvec(), axis=0)
    v = np.gradient(p, t, axis=0, edge_order=2); a = np.gradient(v, t, axis=0, edge_order=2)
    omega = np.gradient(rotvec, t, axis=0, edge_order=2); alpha = np.gradient(omega, t, axis=0, edge_order=2)
    return a, omega, alpha, "filtered_measured_tcp_fallback"


def spatial_regressor(record: dict[str, np.ndarray], *, kinematics: tuple[np.ndarray, np.ndarray, np.ndarray] | None = None) -> np.ndarray:
    """Build tau = Y theta using the same wrench convention as the legacy ID."""
    if kinematics is None:
        a, omega, alpha, _ = _analytic_task_kinematics(record)
    else:
        a, omega, alpha = kinematics
    T = np.asarray(record["T_B_TCP"], dtype=float); J = np.asarray(record["jacobian_TCP"], dtype=float)
    inertia_basis = (np.diag([1.,0.,0.]), np.array([[0,1,0],[1,0,0],[0,0,0.]]),
                     np.array([[0,0,1],[0,0,0],[1,0,0.]]), np.diag([0.,1.,0.]),
                     np.array([[0,0,0],[0,0,1],[0,1,0.]]), np.diag([0.,0.,1.]))
    rows=[]
    for i in range(len(T)):
        R=T[i,:3,:3]; Jv,Jw=J[i,:3,:7],J[i,3:,:7]; effective_a=a[i]-GRAVITY; cols=[]
        for k in range(10):
            m=1. if k==0 else 0.; h_body=np.eye(3)[k-1] if 1<=k<=3 else np.zeros(3); h=R@h_body
            I=R@inertia_basis[k-4]@R.T if k>=4 else np.zeros((3,3))
            force=m*effective_a + np.cross(alpha[i],h) + np.cross(omega[i],np.cross(omega[i],h))
            moment=I@alpha[i] + np.cross(omega[i],I@omega[i]) + np.cross(h,effective_a)
            cols.append(Jv.T@force + Jw.T@moment)
        rows.append(np.stack(cols,axis=1))
    return np.asarray(rows)


def dynamic_inertia_identify(baseline: dict[str, np.ndarray], payload: dict[str, np.ndarray],
                             static_result: dict[str, Any], protocol: dict[str, Any] | None = None,
                             *, max_condition: float = 500.0, max_relative_sigma: float = .60) -> dict[str, Any]:
    """Estimate the six inertia terms after fixing mass and COM."""
    result: dict[str, Any] = {"schema":"payload_id_v2/dynamic_inertia/v1", "stage":"DYNAMIC_ID", "source":"UNOBSERVABLE", "accepted":False}
    if not _record_guard_ok(payload):
        result.update(reason="PAYLOAD_GUARD_ABORT", guard_passed=False); return result
    if not static_result.get("mass_kg") or not np.isfinite(static_result.get("mass_kg", np.nan)):
        result.update(reason="STATIC_MASS_UNAVAILABLE", guard_passed=True); return result
    try:
        tau0,_=align_baseline(baseline,payload); t=_time(payload); rate=_safe_rate(t)
        delta=_filter(np.asarray(payload["tau"],float)-tau0,rate,5.)
        kin_full=_analytic_task_kinematics(payload)
        # ``_analytic_task_kinematics`` returns the three arrays plus an audit
        # label; the regressor consumes only the arrays.
        kin=kin_full[:3]
        Ysamples=spatial_regressor(payload,kinematics=kin).reshape(len(t),7,10)
        m=float(static_result["mass_kg"]); com=np.asarray(static_result["center_of_mass_m"],float); theta_fixed=np.r_[m,m*com]
        residual_delta=delta-(Ysamples[:,:,:4]@theta_fixed)
        trim=max(5,int(.15*rate)); sl=slice(trim,-trim if trim else None)
        Y=Ysamples[sl,:,4:].reshape(-1,6); y=residual_delta[sl].reshape(-1)
        fit=robust_linear_fit(Y,y)
        p=np.asarray(fit["theta"]); Iorigin=np.array([[p[0],p[1],p[2]],[p[1],p[3],p[4]],[p[2],p[4],p[5]]]); Icom=Iorigin-m*(_skew(com).T@_skew(com)); Icom=(Icom+Icom.T)/2
        eig=np.linalg.eigvalsh(Icom); maxeig=float(np.max(eig)) if len(eig) else 0.
        triangle=bool(np.all(2*eig <= np.sum(eig)+max(1e-12,maxeig)*1e-6)) if np.isfinite(eig).all() else False
        psd=bool(np.all(eig>1e-9)) if np.isfinite(eig).all() else False
        std=np.sqrt(np.maximum(np.diag(fit["covariance"]),0.)); scale=np.maximum(np.abs(p),1e-7)
        uncertainty=bool(np.all(std/scale<=max_relative_sigma))
        physical=bool(psd and triangle and np.isfinite(Icom).all())
        observable=bool(fit["rank"]>=6 and fit["condition_number"]<=max_condition and uncertainty and physical)
        result.update(accepted=observable,source="DYNAMIC_ID" if observable else "UNOBSERVABLE",reason="OK" if observable else "INERTIA_UNCERTAIN",guard_passed=True,
          mass_kg=m,center_of_mass_m=com.tolist(),inertia_origin_matrix=Iorigin.tolist(),inertia_matrix=Icom.tolist(),
          parameter_order=list(INERTIA_PARAMETER_ORDER),parameter_covariance=np.asarray(fit["covariance"]).tolist(),parameter_std=std.tolist(),
          observability={"sigma_min":fit["sigma_min"],"sigma_max":fit["sigma_max"],"condition_number":fit["condition_number"],"rank":fit["rank"]},
          residual_rms_Nm=fit["residual_rms_Nm"],robust_scale_Nm=fit["robust_scale_Nm"],outlier_fraction=fit["outlier_fraction"],samples=fit["sample_count"],
          kinematics_source=kin_full[3],physical_checks={"positive_definite":psd,"triangle_inequality":triangle,"finite":bool(np.isfinite(Icom).all()),"relative_uncertainty_ok":uncertainty},
          eigenvalues_kg_m2=eig.tolist(),excitation_protocol=protocol.get("dynamic",{}) if protocol else {})
        return result
    except Exception as exc:
        result.update(reason="DYNAMIC_ESTIMATOR_ERROR",error=str(exc)); return result


def geometry_fallback(mesh_path: Path | str, mass_kg: float) -> dict[str, Any]:
    """Compute COM/inertia from the reconstructed mesh, never from GT."""
    import trimesh
    mesh=trimesh.load(Path(mesh_path),force="mesh",process=True)
    used_hull=False
    volume=float(getattr(mesh,"volume",0.0))
    if not np.isfinite(volume) or volume<=1e-12:
        mesh=mesh.convex_hull; used_hull=True; volume=float(mesh.volume)
    if volume<=1e-12 or not np.isfinite(volume): raise ValueError("reconstructed mesh has no finite volume")
    density=float(mass_kg)/volume; com=np.asarray(mesh.center_mass,float); inertia=np.asarray(mesh.moment_inertia,float)*density; inertia=(inertia+inertia.T)/2
    return {"center_of_mass_m":com.tolist(),"inertia_matrix":inertia.tolist(),"volume_m3":volume,"mesh":str(Path(mesh_path)),"used_convex_hull":used_hull}


def assemble_physical_parameters(static_result: dict[str, Any], dynamic_result: dict[str, Any],
                                 mesh_path: Path | str | None, output: Path | str,
                                 *, nominal_mass_kg: float | None = None) -> dict[str, Any]:
    """Select estimates or explicit fallbacks and write the USD input JSON."""
    static_mass=static_result.get("mass_kg"); mass_ok=static_result.get("accepted") and static_mass is not None and np.isfinite(static_mass) and static_mass>0
    if mass_ok: mass=float(static_mass); mass_source="STATIC_GRAVITY_ID"
    elif static_mass is not None and np.isfinite(static_mass) and static_mass>0:
        mass=float(static_mass); mass_source="STATIC_GRAVITY_ID_UNCERTAIN"
    elif nominal_mass_kg is not None and np.isfinite(nominal_mass_kg) and nominal_mass_kg>0:
        mass=float(nominal_mass_kg); mass_source="CONFIGURED_NOMINAL"
    else: mass=float("nan"); mass_source="UNOBSERVABLE"
    if static_result.get("accepted"):
        com=np.asarray(static_result["center_of_mass_m"],float); com_source="STATIC_GRAVITY_ID"
    elif mesh_path is not None and np.isfinite(mass):
        geom=geometry_fallback(mesh_path,mass); com=np.asarray(geom["center_of_mass_m"],float); com_source="GEOMETRY_FALLBACK"
    else:
        com=np.full(3,np.nan); com_source="UNOBSERVABLE"; geom=None
    if dynamic_result.get("accepted") and np.isfinite(mass):
        inertia=np.asarray(dynamic_result["inertia_matrix"],float); inertia_source="DYNAMIC_ID"
    elif mesh_path is not None and np.isfinite(mass):
        geom=geometry_fallback(mesh_path,mass); inertia=np.asarray(geom["inertia_matrix"],float); inertia_source="GEOMETRY_FALLBACK"
    else:
        inertia=np.full((3,3),np.nan); inertia_source="UNOBSERVABLE"; geom=locals().get("geom")
    # JSON is an interchange format for the eventual USD builder; never emit
    # IEEE NaN/Inf when a parameter is intentionally unobservable. ``None``
    # makes the explicit refusal/fallback visible to downstream consumers.
    def json_value(value):
        if isinstance(value, np.ndarray): return json_value(value.tolist())
        if isinstance(value, (list, tuple)): return [json_value(x) for x in value]
        if isinstance(value, (float, np.floating)) and not np.isfinite(value): return None
        return value
    result={"schema":"real2sim/physical_parameters_v2","estimator":"payload_id_v2_two_stage","mass":json_value(mass),"center_of_mass":json_value(com),"inertia_matrix":json_value(inertia),
            "sources":{"mass":mass_source,"center_of_mass":com_source,"inertia":inertia_source},"static_gravity":static_result,"dynamic_inertia":dynamic_result,
            "geometry_fallback":geom,"gt_used_for_estimation":False}
    out=Path(output);out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(result,indent=2,allow_nan=False))
    return result


def _cli() -> None:
    p=argparse.ArgumentParser(); sub=p.add_subparsers(dest="command",required=True)
    s=sub.add_parser("static");s.add_argument("baseline",type=Path);s.add_argument("payload",type=Path);s.add_argument("output",type=Path);s.add_argument("--protocol",type=Path)
    d=sub.add_parser("dynamic");d.add_argument("baseline",type=Path);d.add_argument("payload",type=Path);d.add_argument("static",type=Path);d.add_argument("output",type=Path);d.add_argument("--protocol",type=Path)
    a=sub.add_parser("assemble");a.add_argument("static",type=Path);a.add_argument("dynamic",type=Path);a.add_argument("output",type=Path);a.add_argument("--mesh",type=Path);args=p.parse_args()
    if args.command=="static":
        protocol=json.loads(args.protocol.read_text()) if args.protocol and args.protocol.exists() else None; out=static_gravity_identify(load_record(args.baseline),load_record(args.payload),protocol)
    elif args.command=="dynamic":
        protocol=json.loads(args.protocol.read_text()) if args.protocol and args.protocol.exists() else None; out=dynamic_inertia_identify(load_record(args.baseline),load_record(args.payload),json.loads(args.static.read_text()),protocol)
    else: out=assemble_physical_parameters(json.loads(args.static.read_text()),json.loads(args.dynamic.read_text()),args.mesh,args.output)
    if args.command!="assemble":args.output.write_text(json.dumps(out,indent=2,allow_nan=False))
    print(json.dumps(out,indent=2))


if __name__=="__main__": _cli()
