"""Passive final evidence snapshot in a preserved transfer actor. No physics step."""
world.pause();world.render()
try:video.stdin.close();video.wait(timeout=30)
except Exception as error:diagnostic_issue('video_close',error)
try:
 for i,cam in enumerate(scene['overview']):cv2.imwrite(str(a.output/f'final_overview_{i}.png'),cv2.cvtColor(np.asarray(cam.get_rgba())[:,:,:3],cv2.COLOR_RGB2BGR))
except Exception as error:diagnostic_issue('final_overview',error)
export_raw_records('observations',rows);export_raw_records('physics_steps',native.physics_steps)
grasps=[e for e in telemetry_events if e['event']=='GRASP_VERIFIED'];releases=[e for e in telemetry_events if e['event']=='RELEASE_START'];physical_open_rows=[r for r in rows if r['phase'] in ('OPEN_1','OPEN_2','OPEN_2_ENDPOINT','FINAL_HOLD')]
controlled_max=max((r['door_angle_deg'] for r in physical_open_rows),default=rows[0]['door_angle_deg'])
transfer_pass=bool(len(grasps)>=2 and base_moves>=1 and max((r['door_angle_deg'] for r in physical_open_rows if r['t']>=grasps[1]['t']),default=grasps[1]['angle_deg'] if len(grasps)>1 else 0.)>(grasps[1]['angle_deg'] if len(grasps)>1 else 0.))
result={'mode':'KNOWN_MODEL_DIAGNOSTIC','asset_id':model.manifest['asset_id'],'actor_pid':os.getpid(),'normal_closed_initialization':True,'initial_actual_angle_deg':rows[0]['door_angle_deg'],'authored_target_deg':goal_deg,'maximum_actual_deg':max_state,'maximum_during_controlled_open_deg':controlled_max,'final_actual_deg':rows[-1]['door_angle_deg'],'mechanism_transfer_success':transfer_pass,'authored_range_success':bool(controlled_max>=goal_deg),'base_moves':base_moves,'successful_regrasps':regrasp_count,'grasp_events':grasps,'release_events':releases,'simulation_duration_s':tick*dt,'wall_since_entry_s':time.perf_counter()-_profile_entry,'wall_duration_includes_preserved_scene_recovery_pauses':True,'peak_pad_load_n':max(max(r['forces_n'].values()) for r in rows),'peak_nonhandle_robot_contact_n':max((c['force_n'] for r in rows for c in r['contacts'] if not c['allowed_pad_target']),default=0.),'minimum_joint_margin_rad':min(r['margin_rad'] for r in rows),'first_tracking_diagnostic':first_divergence,'physical_stop_history':(a.output/'paused.json').read_text() if (a.output/'paused.json').exists() else None,'telemetry_issues':telemetry_issues,'telemetry_field_counts':telemetry_counts,'physics_control_steps':tick,'no_attachment':True,'no_execution_object_actuation':True,'scene_restarts':0,'state_stitching':False,'scene_preserved':True,'video':'contact_baseline.mp4','source_hashes':json.loads((a.output/'source_config_hashes.json').read_text()),'continuation_files':[p.name for p in sorted(a.output.glob('continuation_*.py'))]}
diagnostic_write(a.output/'transfer_result.json',json.dumps(result,indent=2));diagnostic_write(a.output/'events.json',json.dumps(telemetry_events,indent=2));diagnostic_write(a.output/'telemetry_summary.json',json.dumps({'records':tick,'available_field_counts':telemetry_counts,'issues':telemetry_issues,'classification':'PASSIVE_DIAGNOSTIC_ONLY'},indent=2));print('TRANSFER_RESULT',json.dumps({k:v for k,v in result.items() if k not in ('physical_stop_history','source_hashes','telemetry_field_counts','grasp_events','release_events')}),flush=True)
