"""Render complete saved held-out tables; conclusions refer to observed outcomes only."""
import json,csv
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];R=ROOT/'results/generalization_summary';s=json.loads((R/'summary.json').read_text());episodes=list(csv.DictReader((R/'episodes.csv').open()));a=s['groups']['generalization_clutter50'];b=s['groups']['generalization_pose30']
def table(h,rows):return '\n'.join(['| '+' | '.join(h)+' |','|'+'|'.join(['---']*len(h))+'|']+['| '+' | '.join(map(str,r))+' |' for r in rows])
def ci(d):return f"{100*d['ci95'][0]:.1f}–{100*d['ci95'][1]:.1f}%"
def distribution(d):return '无样本' if not d['n'] else f"n={d['n']}; min/Q1/median/Q3/max="+'/'.join(f"{100*d[k]:.3f}%" for k in ['min','q25','median','q75','max'])
near=abs(b['rate']-a['rate'])<=.10
p=['# 冻结 v2 独立泛化验证','本次使用独立 seeds 100–149（固定目标 50 次）与 200–229（目标 xy/yaw 随机 30 次）。两个批次各执行一次，未根据中途结果修改参数，未重新选择阈值。冻结源文件、模型与输入审计见 `results/generalization_audit/`。','## 总体结果',table(['组','成功率','95% Wilson CI','非目标接触','非目标扰动'],[['开发集', '16/20 (80.0%)',ci(s['development']),'0/20','0/20']]+[[label,f"{d['success']}/{d['n']} ({100*d['rate']:.1f}%)",ci(d),f"{d['contact']}/{d['n']}",f"{d['disturbance']}/{d['n']}"] for label,d in [('独立 clutter',a),('独立 target pose',b)]]),'固定目标组'+('达到' if a['criteria_pass'] else '未达到')+'预设的 success ≥75%、contact ≤5%、disturbance ≤5% 点估计标准。目标姿态组成功率相差 '+f"{100*(b['rate']-a['rate']):+.1f}"+' 个百分点，'+('在' if near else '超出')+'预先约定的 10 个百分点描述性范围。小样本 CI 仍需同时考虑，点估计达标不等于对真实成功率下界的保证。','目标变化为 xy 各均匀 ±10 mm、yaw 均匀 ±30°，roll/pitch=0；其他场景、物体类别、相机和推理配置不变。目标 pose manifest 在运行前保存，无按结果重采样。','成功标准仍为实际抬升 ≥8 cm、双指持续接触 >0.1 N、保持 ≥2 s、高度变化 ≤1 cm。非目标接触阈值仍是 >0.05 N；扰动阈值仍是位移 >2 mm 或旋转 >2°。','![总体结果与拒绝候选覆盖分布](results/generalization_summary/generalization.png)','## 完整逐次结果']
for group,label in [('generalization_clutter50','独立 clutter：100–149'),('generalization_pose30','目标 pose：200–229')]:
 er=[r for r in episodes if r['group']==group]
 p+=[f'### {label}',table(['seed','结果','阶段','contact','disturbance','scene 拒绝','pad 拒绝','rank(0-based)','coverage %','规划 s'],[[r['seed'],r['category'],r['last_stage'],r['non_target_contact'],r['disturbance'],r['scene_filtered'],r['pad_filtered'],r['selected_rank'] or '—',f"{100*float(r['selected_coverage']):.3f}" if r['selected_coverage'] else '—',f"{float(r['planning_seconds']):.3f}"] for r in er])]
p+=['## 失败与 coverage 分布']
for name,d in [('clutter50',a),('pose30',b)]:
 p += [name+'：'+str(d['categories']), '4.5% gate 拒绝候选：'+distribution(d['pad_rejected']), '实际成功 selected coverage：'+distribution(d['selected_success_coverage']), '实际失败 selected coverage：'+distribution(d['selected_failure_coverage']), 'coverage ≥4.5% 仍 BAD_CONTACT 的 seeds：'+str(d['bad_contact_above_gate']), '每 episode 原始候选数量：'+str(d['raw_candidate_count'])+'；达到 top-20 上限的 episode 数：'+str(d['episodes_reaching_top20'])]
p+=['无 selected pose 的 episode 单独标记 NO_CANDIDATE；仍保留 SCENE_COLLISION / INSUFFICIENT_PAD_OVERLAP 等原始原因，不从成功率分母剔除。候选原始 score/rank/pose 未变。','## 阈值只读 sensitivity',table(['组','阈值 %','scene 后候选总数','gate 拒绝','无候选 episodes','已成功 pose 被拒绝','已失败 pose 被拒绝','将改选 rank'],[[r['group'].replace('generalization_',''),100*r['threshold'],r['scene_executable_candidates'],r['rejected_candidates'],r['episodes_no_candidate'],r['observed_success_rejected'],r['observed_failure_rejected'],r['selected_rank_would_change']] for r in s['sensitivity']]),'仅将替代阈值应用于保存的候选资格及实际执行结果，没有重新规划、重新推理或重跑物理。未执行 pose 的结果未知，所以这些数不能换算为其他阈值的成功率。4.5% 保持冻结，不依据测试集重新选阈值。','## 与开发集的比较及下一步','新固定目标成功率相对开发集 80% 的变化为 '+f"{100*(a['rate']-.8):+.1f}"+' 个百分点。是否有过拟合不能只看一个比例，需同时考虑 Wilson 区间、目标姿态组和失败层。', '若失败集中在无候选，优先增加可用候选来源的独立研究；当实际输出普遍少于 top-20 时，仅提高 K 不会自动产生更多候选，需要进一步区分 NMS、感知视角和机器人可执行性限制。本次没有改变这些配置。coverage 通过但物理失败的案例应继续诊断该几何量，不能直接用测试集提高阈值。','## 文件与复现','启动和增量文件定义见 `GENERALIZATION_IMPLEMENTATION.md`。完整表与候选分布为 `results/generalization_summary/episodes.csv`、`candidates.csv`、`sensitivity.csv`、`summary.json`。各 episode JSON 和 trace 保存在两个独立批次目录；原开发结果完整保留。']
p+=['## 本次判断与具体剩余问题',
'两组均达到预先定义的点估计验收标准，姿态组与固定目标组只差 +0.7 个百分点。相对原开发集 80%，未观察到明显性能过拟合或只适用于固定 box pose 的现象。可在当前 box、三邻居、轻度 clutter 的范围内认为执行层基本通过，进入有界的 support graph / 多物体选择研究；下一阶段应保留本冻结执行器作基线，并单独检验新增决策层。当前结果不等于新类别或复杂堆叠的验证。',
'固定目标失败：seed 110 为 selected rank 5、coverage 57.71% 的 LIFT 阶段 SCENE_COLLISION；seed 121 无候选通过 pad gate。目标姿态失败为 seed 225 的 pad gate 耗尽候选。没有 BAD_CONTACT、SLIP 或 DROP。',
'seed 110 的保存状态只读 PlanningScene 对照：actual 起点与 fr3_hand/clutter_1 冲突，Cartesian fraction=0；ideal commanded 起点有效且 fraction=1；将关节偏差减少一半的数学对照也可行。其 micro 端点位置误差约 1.067 mm；目标在 micro 中随动上升且保持双指接触。没有发送物理执行命令或改变增益。该失败属于残余跟踪偏差触发的规划安全拦截，不能归为 pad 物理夹持失败，也不能记作真实非目标接触。证据为 results/generalization_lift110/comparison.json。',
'两组实际成功 selected coverage 最小值分别为 22.05% 和 11.83%，明显高于 4.5%。0–10% sensitivity 没有拒绝任何实际执行的成功或失败 pose，但可能改变最高分可选 rank；替代候选未执行，结果未知。这说明当前执行层在本测试范围泛化良好，同时测试没有充分挑战 4.5% 附近边界，不能由此断言该数值最优。保持 4.5%，不重新选阈值。',
'Sensitivity 中 4.5/7.5/10% 的所选 rank 和无候选 episode 数完全相同。降低到 2% 会改变固定目标组 2 个 episode 的选择；0% 会改变固定目标组 24 个、姿态组 1 个 episode。未执行这些替代 pose，因此不宣称降低阈值能增加物理成功率。',
'实际每次网络输出仅 5–9 / 5–12 个候选，80 次都没达到 K=20 上限。因此仅提高 top-K 截断值不会增加这批已有输出。若后续专门解决无候选尾部，应先观察 NMS 前候选或研究多视角是否增加可行候选；ranking 本身不能产生候选。本次未改变 NMS、视角或 ranking。',
'接触和扰动均观察到 0 次，但其各自 95% Wilson 上界为固定目标约 7.13%、目标姿态约 11.35%；有限样本尚不能证明真实事件率一定低于 5%。按用户规定的经验比例验收通过，保留这一不确定性。']
(ROOT/'GENERALIZATION_RESULTS.md').write_text('\n\n'.join(p)+'\n')
